Add taxonomy test
wizeline/factiva-news-python pull request #2
Opened 2021-05-12 05:04 UTC by cerritows

## Description
- Add test scenario for taxonomy class
- Fix variable initialization
- Add to ´init´

2021-05-12 13:53 UTC, vic3r requested changes
the code_list is not being used

2021-05-12 13:53 UTC, vic3r commented on test/taxonomy.py
> +code_list = ["US0378331005", "US0231351067", "US5949181045", "US4523531083"]
code_list is not being used

2021-05-12 13:53 UTC, vic3r commented on test/taxonomy.py
> +company = taxonomy.get_company('isin', company_code='PLUNMST00014')
I was thinking, may the code_type (first argument) could be a kwarg like the company_code, in order to be more friendly

2021-05-13 19:11 UTC, cerritows commented on test/taxonomy.py
> +company = taxonomy.get_company('isin', company_code='PLUNMST00014')
I thought about it. It would look better, however the way to call the method would stay pretty much the same.

2021-05-13 19:49 UTC, vic3r approved these changes
👍

2021-05-14 03:31 UTC, merged