Add snapshot updates
wizeline/factiva-news-python pull request #3
Opened 2021-05-13 07:11 UTC by cerritows

This PR:
- Refactors previously existing code to be separated into different files
    - Separates the classes `ExplainJob`, `AnalyticsJob` and `ExtractionJob` into its own file `jobs.py`
    - Moves methods for handling jobs from `BulkNewsBase` to `BulkNewsJob`
    - Replaces custom logic for handling logic inside `Snapshot` with the job's own methods
- Adds required code to handle snapshot updates.
   - Adds class `UpdateJob` which extends from `ExtractionJob``
- Adds test scenario for `UpdateJob`

2021-05-14 20:51 UTC, vic3r requested changes
There may be some changes that could be applied

2021-05-14 20:51 UTC, vic3r commented on src/factiva/news/bulknews.py
> +            # TODO_REPLACE THIS WITH A CONSTANT
Did you forget the TODO?

2021-05-14 20:51 UTC, vic3r commented on src/factiva/news/bulknews.py
> +        else:  # TODO: Add InvalidQuery, invalid syntax error which returns a 400
Should we consider this TODO?

2021-05-14 20:51 UTC, vic3r commented on src/factiva/news/snapshot/snapshot.py
> +            self.last_extraction_job = ExtractionJob(snapshot_id=snapshot_id, api_key=self.api_user.api_key)
I think it's being created another instance of APIKeyUser inside ExtractionJob isn't it? don't you think that in BulkNewsJob would be enough to pass down the same object. Otherwise there will be two references of APIKeyUser

2021-05-14 20:51 UTC, vic3r commented on src/factiva/news/snapshot/snapshot.py
> +            self.query = SnapshotQuery('')
Maybe we could handle in some way SnapshotQuery() instead of SnapshotQuery('')

2021-05-14 20:51 UTC, vic3r commented on src/factiva/news/snapshot/snapshot.py
> +        parameters used by `submit_analyttics_job`. Then, monitors the job until
```suggestion
        parameters used by `submit_analytics_job`. Then, monitors the job until
```

2021-05-14 20:51 UTC, vic3r commented on src/factiva/news/snapshot/snapshot.py
> +    def download_extraction_files(self):
I think you can receive here as below a download_path in parameters `download_extraction_files(self, download_path=None):`
So `self.last_extraction_job.download_job_files(download_path)` can use the path

2021-05-14 20:51 UTC, vic3r commented on src/factiva/news/snapshot/snapshot.py
> +    def download_update_files(self):
you could receive the `download_path` as a parameter as well, so you could use `self.last_update_job.download_job_files(download_path)`

2021-05-14 20:51 UTC, vic3r commented on src/factiva/news/snapshot/jobs.py
> +    def process_job(self, payload, path = None):
I think a default value for payload could be as well None, so there is no need to pass down the `process_job(payload=None, path=download_path)`instead it will be `process_job(path=download_path)`

2021-05-14 20:51 UTC, vic3r commented on src/factiva/news/snapshot/snapshot.py
> +        return self.last_update_job.process_job(payload=None, path=download_path)
I put a comment about this in `UpdateJob`

2021-05-14 23:58 UTC, vic3r commented on src/factiva/news/bulknews.py
> +            self.job_state = response_data['data']['attributes']['current_state']
I think this `self.job_state` works only for snapshots, in streams the expected response after submiting a job for a subscription is `response_data['data']['attributes']['job_status']`

2021-05-18 05:02 UTC, cerritows commented on src/factiva/news/bulknews.py
> +        open(download_path, 'wb').write(response.content)
I think so too. However, there is nothing we can do to handle the exception other than bubbling it up. As for the return value, I added it. 👍

2021-05-18 05:05 UTC, cerritows commented on src/factiva/news/snapshot/jobs.py
> +        return source['data']['id'].split('-')[-3:-1]
The structure in the comment. A snapshot update has an ID in the format `API_URL/dj-synhub-extraction-{USER-KEY}-{SNAPSHOT_ID}-{UPDATE_TYPE}-{DATETIME}` We are taking the last three (snapshot_id, update_type and datetime). I updated the comment to be clearer

2021-05-18 05:22 UTC, cerritows commented on src/factiva/news/bulknews.py
> +            # TODO_REPLACE THIS WITH A CONSTANT
I'm leaving it out of the scope for this PR. A believe an specific PR to replace all the appearances of these constants needs to be made

2021-05-18 05:24 UTC, cerritows commented on src/factiva/news/bulknews.py
> +        else:  # TODO: Add InvalidQuery, invalid syntax error which returns a 400
It was there before. I think it falls out of the scope of this PR since more research needs to be done to add this case

2021-05-18 05:27 UTC, cerritows commented on src/factiva/news/snapshot/snapshot.py
> +            self.last_extraction_job = ExtractionJob(snapshot_id=snapshot_id, api_key=self.api_user.api_key)
Done 👍

2021-05-18 05:32 UTC, cerritows commented on src/factiva/news/snapshot/snapshot.py
> +            self.query = SnapshotQuery('')
More in depth discussion is required, since we need to consider whether there is logic in having a query without a clause. Rather, I think the correct way to handle this one is to not initialize the query object. This represents way better the object, because when a snapshot_id is given, there is no way to know the query it was created with (unless the user specifies it, and even then, we have no way of knowing if that is the right one)

2021-05-18 16:11 UTC, cerritows commented on src/factiva/news/bulknews.py
> +        self.api_user = APIKeyUser.create_api_user(api_user, request_userinfo)
`create_api_user` returns the same instance if an instance of APIKeyUser is passed, it doesn't create another one

2021-05-18 20:20 UTC, vic3r approved these changes
👍

2021-05-18 22:05 UTC, merged